### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kngwyu** [kngwyu/num-alias#1]
- [ ] impl Bit operators for int_alias
- [ ] impl Neg for signed int
- [x] impl Neg for float
- [ ] add some debug formats for both aliases
- [x] member of tuple aliases should be public
- [ ] add wrapped alias(use Option as inner type)
